import { Octokit } from "octokit";

/**
 * createPrForWorkflow - create a branch, add/update workflow file, and open a PR
 * @param {Octokit} octokit - authenticated Octokit instance
 * @param {string} owner
 * @param {string} repo
 * @param {string} filePath - path in repo (e.g. .github/workflows/ci.yml)
 * @param {string} content - raw file content (string)
 * @param {string} branchName - optional branch name (auto-generated if omitted)
 */
export async function createPrForWorkflow(octokit, owner, repo, filePath, content, branchName) {
  if (!octokit) throw new Error("Octokit client required");

  // Get repository info to determine default branch
  const { data: repoInfo } = await octokit.rest.repos.get({ owner, repo });
  const defaultBranch = repoInfo.default_branch || "main";

  // Get sha of default branch
  const { data: refData } = await octokit.rest.git.getRef({ owner, repo, ref: `heads/${defaultBranch}` });
  const baseSha = refData.object.sha;

  // Prepare branch name
  const time = new Date().toISOString().replace(/[:.]/g, "-");
  const br = branchName || `pipeline-gen/ci-${time}`;

  // Create branch (ref)
  try {
    await octokit.rest.git.createRef({ owner, repo, ref: `refs/heads/${br}`, sha: baseSha });
  } catch (err) {
    if (err.status === 422) {
      // branch already exists — continue
    } else {
      throw err;
    }
  }

  // Create or update file on the new branch
  const contentBase64 = Buffer.from(content, "utf8").toString("base64");
  const message = "chore(ci): add generated CI workflow (pipeline-gen)";

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message,
    content: contentBase64,
    branch: br,
  });

  // Create a pull request
  const prTitle = "[pipeline-gen] Proposed CI workflow";
  const prBody = "This PR was generated by pipeline-gen GitHub App. Please review and adjust as needed.";

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: prTitle,
    head: br,
    base: defaultBranch,
    body: prBody,
  });

  return pr;
}
